export enum ROUTES {
  NewAds = 'NewAds',
  Bets = 'Bets',
  Delivery = 'Delivery',
  HomeStack = 'HomeStack',
  Account = 'Account',
  GuestAccount = 'GuestAccount',
  AccountStack = 'AccountStack',
  Home = 'Home',
  SubCategory = 'SubCategory',
  LotList = 'LotList',
  Lot = 'Lot',
  Auth = 'Auth',
  OnBoarding = 'OnBoarding',
  PersonalData = 'PersonalData',
  MyAds = 'MyAds',
  Notifications = 'Notifications',
  Currency = 'Currency',
  Language = 'Language',
  Settings = 'Settings',
  Password = 'Password',
  RootStack = 'RootStack',
}
